# =============================================================================
# BASE CONFIGURATION
# =============================================================================

version: "3.7"

# =============================================================================
# SERVICES
# =============================================================================

services:

# =============================================================================
# CORONA TRACKER
# =============================================================================

  coronatracker:
    container_name: ${CONTAINER_NAME}
    env_file: ./.env
    build:
      context: ./${PATH_DOCKERFILE}
      dockerfile: Dockerfile
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "20"
    links:
      - cache
    depends_on:
      - cache
    volumes:
      - coronatracker:/var/log/coronatracker
    networks:
      - coronatracker

# =============================================================================
# REDIS CACHE
# =============================================================================

  cache:
    image: redis:alpine3.11
    container_name: cache
    command: redis-server --requirepass corona
    restart: unless-stopped
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "20"
    volumes:
      - cache:/var/lib/redis
    networks:
      - coronatracker

# =============================================================================
# NETWORK
# =============================================================================

networks:
  coronatracker:

# =============================================================================
# VOLUMES
# =============================================================================

volumes:
  cache:
    driver: local
  coronatracker:
    driver: local
