# =============================================================================
# BASE CONFIGURATION
# =============================================================================

version: "3.7"

# =============================================================================
# SERVICES
# =============================================================================

services:

# =============================================================================
# CORONA API TRACKER
# =============================================================================

  corona-api-tracker:
    container_name: ${CONTAINER_NAME}
    env_file: ./.env
    build:
      context: ./${PATH_DOCKERFILE}
      dockerfile: Dockerfile
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "20"
    networks:
      - corona-api-tracker

# =============================================================================
# NETWORKS
# =============================================================================

networks:
  corona-api-tracker:
