# =============================================================================
# BASE CONFIGURATION
# =============================================================================

version: "3.7"

# =============================================================================
# SERVICES
# =============================================================================

services:

# =============================================================================
# CORONA TRACKER
# =============================================================================

  coronatracker:
    container_name: coronatracker
    env_file: ./.env
    build:
      context: ./${PATH_DOCKERFILE}
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "20"
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - coronatracker:/var/log/coronatracker
    networks:
      - coronatracker

# =============================================================================
# MONGO DATABASE
# =============================================================================

  mongo:
    image: mongo:4.2-bionic
    container_name: mongo
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodata:/data/db
    networks:
      - coronatracker

# =============================================================================
# NETWORK
# =============================================================================

networks:
  coronatracker:

# =============================================================================
# VOLUMES
# =============================================================================

volumes:
  mongodata:
    driver: local
  coronatracker:
    driver: local
